### PR TITLE
bug: fix to use user defined default sampling rule for X-Ray

### LINKED ISSUE #18283: X-Ray sampling default rule cannot be mutated
*Description*:
As part of the X-Ray tracing integration, users can define a custom file (or manifest) with rules which control the sampling rate of traces to be sent to X-Ray. In other words, they can select only a percentage of requests to be traced to mitigate costs. A sampling rule manifest consists of a default rule and many custom rules (see [docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling) for more). 

The problem is that if a user provides a custom manifest with a newly-defined, valid default rule, and no custom rules, Envoy ignores the user's modified default rule and uses the built-in default rule instead. This logic is here:

https://github.com/envoyproxy/envoy/blob/0dfa3df2ea413fa25ab2cb206957e6ec150d7271/source/extensions/tracers/xray/localized_sampling.cc#L180-L182

This can be fixed with a one-line change to return this instead:

```cc
return shouldTrace(custom_manifest_.defaultRule());
```

Happy to make this PR, but not sure if my C is strong enough to add a unit test.

### PR DESCRIPTION
**Pull request by shsahu**
Signed-off-by: Shweta Sahu <sshwat@amazon.com>

Commit Message: bug: fix to use user defined default sampling rule for x-ray
Additional Description: If a user provides a custom manifest with a newly-defined, valid default rule, and no custom rules, Envoy ignores the user's modified default rule and uses the built-in default rule instead. With this fix, envoy will use user defined default rule.

Risk Level: Low
Testing: unit test
Docs Changes: N/A
Release Notes: N/A
Platform Specific Features: N/A
[Optional Runtime guard:]
[Optional Fixes #18283]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional API Considerations:]

### CODE REVIEW

File: source/extensions/tracers/xray/localized_sampling.h [hunk 1]
```diff
@@ -138,33 +138,24 @@ class LocalizedSamplingStrategy : public SamplingStrategy {
...
-  /**
-   * @return the default manifest. Mainly for unit testing purposes.
-   */
-  const LocalizedSamplingManifest& defaultManifest() const { return default_manifest_; }
+  const LocalizedSamplingManifest manifest() const { return manifest_; }
 
 private:
   bool shouldTrace(LocalizedSamplingRule& rule);
-  LocalizedSamplingManifest default_manifest_;
-  LocalizedSamplingManifest custom_manifest_;
```
Comment (shsahu) [inline source/extensions/tracers/xray/localized_sampling.h:165]: [The default_rule_ of LocalizedSamplingManifest is initialized with built-in default rule](https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/xray/localized_sampling.cc#L91), hence there is no need to maintain a separate default_manifest_ just to maintain the built-in default rule.

File: source/extensions/tracers/xray/localized_sampling.h [hunk 2]
```diff
@@ -138,33 +138,24 @@ class LocalizedSamplingStrategy : public SamplingStrategy {
...
+  LocalizedSamplingManifest manifest_;
   TimeSource& time_source_;
-  bool use_default_;
```
Comment (shsahu) [inline source/extensions/tracers/xray/localized_sampling.h:167]: This was only used by tests and was used to check if user defined custom rules are not in use. It was skipping checking for user defined default rules.
Removed this and added a simple logic in tests for verification.

File: test/extensions/tracers/xray/localized_sampling_test.cc [hunk 3]
```diff
@@ -616,6 +704,58 @@ TEST_F(LocalizedSamplingStrategyTest, NoMatchingPath) {
...
+}
+)EOF";
+
+  LocalizedSamplingStrategy strategy{rules_json, rng, time_system_};
+  ASSERT_FALSE(strategy.manifest().hasCustomRules());
+
+  SamplingRequest req;
+  req.http_url_ = "/";
+  ASSERT_TRUE(strategy.shouldTrace(req)); // The default rule traces the first request each second
+  int i = 10;
```
Comment (lavignes) [inline test/extensions/tracers/xray/localized_sampling_test.cc]: nit: Id just use a regular counting-up for loop
```
for (int i = 0; i < 10; ++i) {
    // ...
}
```

File: source/extensions/tracers/xray/localized_sampling.h [hunk 4]
```diff
@@ -138,33 +138,24 @@ class LocalizedSamplingStrategy : public SamplingStrategy {
...
-   * Determines if an incoming request matches one of the sampling rules in the local manifests.
+   * Determines if an incoming request matches one of the sampling rules in the local manifest.
    * If a match is found, then the request might be traced based on the sampling percentages etc.
    * determined by the matching rule.
    */
   bool shouldTrace(const SamplingRequest& sampling_request) override;
 
   /**
-   * Determines whether default rules are in effect. Mainly for unit testing purposes.
+   * @return the manifest. Mainly for unit testing purposes.
```
Comment (lavignes) [inline source/extensions/tracers/xray/localized_sampling.h]: Does Envoy do any of this javadoc style? You could also just remove the comment. It's just a getter.

**Review by lavignes — COMMENTED** [review]
looks good

**Comment by abaptiste** [comment]
LGTM

File: source/extensions/tracers/xray/localized_sampling.h (hunk 4 above)
Comment (shsahu) [reply source/extensions/tracers/xray/localized_sampling.h]: Sure will remove, was just following the convention here.
